# Site settings
title: David Trussel
email:
description: >-
  C++ / Python / Embedded Linux
baseurl: ""
url: "https://trussel.ch"
github_username: dtrussel
lang: en

author:
  name: David Trussel

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .github/
